### ISSUE TITLE
gpu memory leak

### ISSUE THREAD

**Issue by domino20** [lijun99/cuAmpcor#2]
hey,

After I do this (objOffset.runAmpcor), it seems that the gpu memory is always occupied (a few GB for my data). Is the memory released after running in the code?

Since I need to run this a few times for different image pairs, the errors comes out when I run this for the second pair.Then i notice the memory seems not released. The program stops at "cuOverSampler.cpp:50 code=5(cufftPlanMany(&forwardPlan, NRANK, n, NULL, 1, imageSize, NULL, 1, fImageSize, CUFFT_C2C, nImages"

**Comment by lijun99** [comment]
To reduce the overhead of allocating/deallocating, (most) gpu memory are retained during the batched processing. Once the life cycle of objOffset ends, such as at the end of the script or python session, the gpu memory should be released.

**Comment by EllenLee183** [comment]
I encountered the same problem. It seems that after executing objOffset, the GPU memory was not released in time. In my case, when a script made two consecutive InSAR task, the memory occupied for the first time was 5269MB, and for the second time, the GPU memory  memory occupied is 10000+MB, and the GPU memory cannot be released until all python codes are executed. If my script executes n differential interference patterns, will theGPU memory resources occupied when executing the last interference pattern be n*5269MB?

**Comment by domino20** [comment]
> To reduce the overhead of allocating/deallocating, (most) gpu memory are retained during the batched processing. Once the life cycle of objOffset ends, such as at the end of the script or python session, the gpu memory should be released.

I tried del objOffset, gc.collect(), but the gpu memory is not released. It seems that I can not free it in my python codes unless my script ends... Ant suggestions? Is it possible to free the occupied variables in your codes

**Comment by lijun99** [comment]
Indeed, the problem arises when repeating runAmpcor in the same python session. 

[Here is the fix](https://github.com/lijun99/isce2/commit/51af91d211ca6be7b2cf3c645bda3f5b1eaadeb2). You may pull from my isce2 remote, or simply download and replace the two updated files. 

Let me know whether it works.

**Comment by domino20** [comment]
> Indeed, the problem arises when repeating runAmpcor in the same python session.
> 
> [Here is the fix](https://github.com/lijun99/isce2/commit/51af91d211ca6be7b2cf3c645bda3f5b1eaadeb2). You may pull from my isce2 remote, or simply download and replace the two updated files.
> 
> Let me know whether it works.

It works very well now. Thanks.
